services:
  opcua-server:
    image: aaronzi/opcua-timeseries:latest
    container_name: opcua-timeseries-server
    ports:
      - "4840:4840"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - opcua-network
    restart: unless-stopped
    depends_on:
      - influxdb
    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; from server.client_test import test_connection; asyncio.run(test_connection('opc.tcp://localhost:4840/opcua/server'))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxpassword
      - DOCKER_INFLUXDB_INIT_ORG=htw
      - DOCKER_INFLUXDB_INIT_BUCKET=opcua-timeseries
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=S18VeAlq042B4naMX31oqIaSGmUmOLAC-DV3VIdkxDJuAhTXLTVFEchyTSmCcUAmB7Wu94KgExzV8gJaDjzR3Q==
    networks:
      - opcua-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  telegraf:
    image: telegraf:1.29.1
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - opcua-network
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
      opcua-server:
        condition: service_healthy

  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - opcua-network
    restart: unless-stopped
    depends_on:
      - influxdb

volumes:
  influxdb-data:
    driver: local
  influxdb-config:
    driver: local
  grafana-data:
    driver: local

networks:
  opcua-network:
    driver: bridge
