version: '3.8'

services:
  opcua-server:
    image: aaronzi/opcua-timeseries:1.0.0
    container_name: opcua-timeseries-server
    ports:
      - "4840:4840"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - opcua-network
    restart: unless-stopped
    depends_on:
      - influxdb
    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; from server.client_test import test_connection; asyncio.run(test_connection())"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  influxdb:
    image: influxdb:2.7-alpine
    container_name: opcua-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=opcua-org
      - DOCKER_INFLUXDB_INIT_BUCKET=opcua-timeseries
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=opcua-admin-token-please-change-this
    networks:
      - opcua-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  grafana:
    image: grafana/grafana:10.2.0
    container_name: opcua-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-influxdb-datasource
    networks:
      - opcua-network
    restart: unless-stopped
    depends_on:
      - influxdb

volumes:
  influxdb-data:
    driver: local
  influxdb-config:
    driver: local
  grafana-data:
    driver: local

networks:
  opcua-network:
    driver: bridge
